### ISSUE TITLE
Issues about missing files

### ISSUE THREAD

**Issue by lzero1115** [pzpzpzp1/wassersplines#1]
Thank you for your attractive work! 
But it seems like there are some files missing in your repository. When I try to run the first block of cnf-sinkhorn-demo.ipynb, it shows FileNotFoundError: [Errno 2] No such file or directory: 'results/experiment_fish234_signedcurl_even/models/state_final.tar'.
Or should I generate results directory by myself using your code?

**Comment by pzpzpzp1** [comment]
You're meant to generate those yourself
